apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: shared-infra
  labels:
    app.kubernetes.io/name: "redis"
    app.kubernetes.io/version: "7"
    app.kubernetes.io/component: "cache"
    app.kubernetes.io/managed-by: "kubectl"
    environment: "lab"
    lab_id: "lab-k8s-01"
    lab_owner: "jose.mussauer"
type: Opaque
stringData:
  REDIS_PASSWORD: "redis123!"
