apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: shared-infra
  labels:
    app.kubernetes.io/name: "postgresql"
    app.kubernetes.io/version: "16"
    app.kubernetes.io/component: "database"
    app.kubernetes.io/managed-by: "kubectl"
    environment: "lab"
    lab_id: "lab-k8s-01"
    lab_owner: "jose.mussauer"
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres123!"
  REALTPMSYS_PASSWORD: "realtpmsys123!"
  AMFIT_PASSWORD: "amfit123!"
